backend:
  name: github
  repo: aarushiyadav123-create/dakshyadav.co.in
  branch: main
  base_url: https://dakshyadav.co.in
  auth_endpoint: .netlify/auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blogs & Thoughts"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
