backend:
  name: git-gateway
  branch: main # अगर आपकी मुख्य ब्रांच master है, तो यहाँ master लिखें

media_folder: "images" # जहाँ फोटोज़ सेव होंगी
public_folder: "/images"

collections:
  - name: "blog"
  - label: "Blogs & Thoughts"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
